// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.5.1
// source: acceslan.proto

package site

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SiteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SiteRequest) Reset() {
	*x = SiteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acceslan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteRequest) ProtoMessage() {}

func (x *SiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acceslan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteRequest.ProtoReflect.Descriptor instead.
func (*SiteRequest) Descriptor() ([]byte, []int) {
	return file_acceslan_proto_rawDescGZIP(), []int{0}
}

func (x *SiteRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SiteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site        string  `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Access      bool    `protobuf:"varint,2,opt,name=access,proto3" json:"access,omitempty"`
	Elapsedtime float32 `protobuf:"fixed32,3,opt,name=elapsedtime,proto3" json:"elapsedtime,omitempty"`
}

func (x *SiteResponse) Reset() {
	*x = SiteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acceslan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteResponse) ProtoMessage() {}

func (x *SiteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acceslan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteResponse.ProtoReflect.Descriptor instead.
func (*SiteResponse) Descriptor() ([]byte, []int) {
	return file_acceslan_proto_rawDescGZIP(), []int{1}
}

func (x *SiteResponse) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *SiteResponse) GetAccess() bool {
	if x != nil {
		return x.Access
	}
	return false
}

func (x *SiteResponse) GetElapsedtime() float32 {
	if x != nil {
		return x.Elapsedtime
	}
	return 0
}

var File_acceslan_proto protoreflect.FileDescriptor

var file_acceslan_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x63, 0x63, 0x65, 0x73, 0x6c, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x73, 0x69, 0x74, 0x65, 0x22, 0x1f, 0x0a, 0x0b, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x5c, 0x0a, 0x0c, 0x53, 0x69, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65,
	0x64, 0x74, 0x69, 0x6d, 0x65, 0x32, 0x3e, 0x0a, 0x0b, 0x53, 0x69, 0x74, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x53, 0x69, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x73,
	0x69, 0x74, 0x65, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x12, 0x2e, 0x73, 0x69, 0x74, 0x65, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_acceslan_proto_rawDescOnce sync.Once
	file_acceslan_proto_rawDescData = file_acceslan_proto_rawDesc
)

func file_acceslan_proto_rawDescGZIP() []byte {
	file_acceslan_proto_rawDescOnce.Do(func() {
		file_acceslan_proto_rawDescData = protoimpl.X.CompressGZIP(file_acceslan_proto_rawDescData)
	})
	return file_acceslan_proto_rawDescData
}

var file_acceslan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_acceslan_proto_goTypes = []interface{}{
	(*SiteRequest)(nil),  // 0: site.SiteRequest
	(*SiteResponse)(nil), // 1: site.SiteResponse
}
var file_acceslan_proto_depIdxs = []int32{
	0, // 0: site.SiteService.Site:input_type -> site.SiteRequest
	1, // 1: site.SiteService.Site:output_type -> site.SiteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_acceslan_proto_init() }
func file_acceslan_proto_init() {
	if File_acceslan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_acceslan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acceslan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SiteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_acceslan_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_acceslan_proto_goTypes,
		DependencyIndexes: file_acceslan_proto_depIdxs,
		MessageInfos:      file_acceslan_proto_msgTypes,
	}.Build()
	File_acceslan_proto = out.File
	file_acceslan_proto_rawDesc = nil
	file_acceslan_proto_goTypes = nil
	file_acceslan_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SiteServiceClient is the client API for SiteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SiteServiceClient interface {
	Site(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*SiteResponse, error)
}

type siteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSiteServiceClient(cc grpc.ClientConnInterface) SiteServiceClient {
	return &siteServiceClient{cc}
}

func (c *siteServiceClient) Site(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*SiteResponse, error) {
	out := new(SiteResponse)
	err := c.cc.Invoke(ctx, "/site.SiteService/Site", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SiteServiceServer is the server API for SiteService service.
type SiteServiceServer interface {
	Site(context.Context, *SiteRequest) (*SiteResponse, error)
}

// UnimplementedSiteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSiteServiceServer struct {
}

func (*UnimplementedSiteServiceServer) Site(context.Context, *SiteRequest) (*SiteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Site not implemented")
}

func RegisterSiteServiceServer(s *grpc.Server, srv SiteServiceServer) {
	s.RegisterService(&_SiteService_serviceDesc, srv)
}

func _SiteService_Site_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServiceServer).Site(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/site.SiteService/Site",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServiceServer).Site(ctx, req.(*SiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SiteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "site.SiteService",
	HandlerType: (*SiteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Site",
			Handler:    _SiteService_Site_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "acceslan.proto",
}
